version: '3.8'
services:
  stats-server:
    build: ./stat_svc/stat_svc_server
    image: stat_server
    container_name: stats-server-container
    ports:
      - "9090:9090"

    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_STATS_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_STATS_USERNAME=postgres
      - SPRING_DATASOURCE_STATS_PASSWORD=root
  stats-db:
    image: postgres:15.1-alpine
    container_name: stats-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stats

  main-service:
    build: ./main_svc
    image: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_MAIN_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_MAIN_USERNAME=postgres
      - SPRING_DATASOURCE_MAIN_PASSWORD=root
  ewm-db:
    image: postgres:15.1-alpine
    container_name: main-db-container
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main
